apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcepatches.mmilev.io
spec:
  group: mmilev.io
  names:
    kind: ResourcePatch
    plural: resourcepatches
    singular: resourcepatch
    listKind: ResourcePatchList
  scope: Cluster
  versions:
  - deprecated: false
    name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
